// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tankradar.MAUI.Data;

#nullable disable

namespace Tankradar.MAUI.Data.Migrations
{
    [DbContext(typeof(TankradarDbContext))]
    [Migration("20261004180805_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Tankradar.MAUI.Data.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpsUsage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSortOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultView")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
