// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tankradar.MAUI.Data;

#nullable disable

namespace Tankradar.MAUI.Data.Migrations
{
    [DbContext(typeof(TankradarDbContext))]
    partial class TankradarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Tankradar.MAUI.Data.FavoriteEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.HasIndex("GroupId", "StationId")
                        .IsUnique();

                    b.ToTable("FavoriteEntries", (string)null);
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.FavoriteGroupEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FavoriteGroups", (string)null);
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.FuelTypeSettingEntity", b =>
                {
                    b.Property<string>("FuelTypeKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("FuelTypeKey");

                    b.ToTable("FuelTypeSettings", (string)null);
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.PriceEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuelTypeKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RetrievedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId", "FuelTypeKey", "RetrievedUtc");

                    b.ToTable("PriceEntries", (string)null);
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.StationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailsUpdatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpeningTimesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Place")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("WholeDay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Latitude", "Longitude");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GpsUsage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultSortOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultView")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserSettings", (string)null);
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.FavoriteEntryEntity", b =>
                {
                    b.HasOne("Tankradar.MAUI.Data.FavoriteGroupEntity", "Group")
                        .WithMany("Entries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tankradar.MAUI.Data.StationEntity", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.PriceEntryEntity", b =>
                {
                    b.HasOne("Tankradar.MAUI.Data.StationEntity", "Station")
                        .WithMany("PriceEntries")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.FavoriteGroupEntity", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Tankradar.MAUI.Data.StationEntity", b =>
                {
                    b.Navigation("PriceEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
